name: gr310
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp>=1.82.0
  - cmake>=3.26
  - cxx-compiler
  - gcc>=11.2
  - gnuradio>=3.10
  - gxx_linux-64
  - pybind11
  - python>=3.12
  - uhd
  - volk
