name: gr310
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - adwaita-icon-theme
  - alsa-lib
  - alsa-plugins
  - aom
  - at-spi2-atk
  - at-spi2-core
  - atk-1.0
  - attr
  - attrs
  - binutils_impl_linux-64
  - binutils_linux-64
  - boost-cpp
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - clang-format
  - clang-format-14
  - click
  - click-plugins
  - cmake
  - cryptography
  - cxx-compiler
  - cycler
  - dbus
  - epoxy
  - expat
  - ffmpeg
  - fftw
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - fribidi
  - gcc
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdk-pixbuf
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gnuradio
  - gnuradio-core
  - gnuradio-grc
  - gnuradio-iio
  - gnuradio-qtgui
  - gnuradio-soapy
  - gnuradio-uhd
  - gnuradio-video-sdl
  - gnuradio-zeromq
  - gnutls
  - graphite2
  - gsl
  - gst-plugins-base
  - gstreamer
  - gstreamer-orc
  - gtk3
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - hicolor-icon-theme
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - jack
  - jpeg
  - jsonschema
  - kernel-headers_linux-64
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libad9361-iio
  - libaio
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang-cpp14
  - libclang13
  - libcodec2
  - libcups
  - libcurl
  - libdb
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libffi
  - libflac
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgirepository
  - libglib
  - libgomp
  - libiconv
  - libidn2
  - libiio-c
  - liblapack
  - libllvm14
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - librsvg
  - libsanitizer
  - libsndfile
  - libsodium
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtasn1
  - libthrift
  - libtiff
  - libtool
  - libudev1
  - libunistring
  - libusb
  - libuuid
  - libuv
  - libva
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - libzlib
  - lxml
  - lz4-c
  - mako
  - markupsafe
  - matplotlib-base
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nettle
  - nspr
  - nss
  - numpy
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pango
  - pcre
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - ply
  - portaudio
  - pthread-stubs
  - pulseaudio
  - pybind11
  - pybind11-abi
  - pybind11-global
  - pycairo
  - pycparser
  - pygobject
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyqtgraph
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pyyaml
  - pyzmq
  - qt-main
  - qwt
  - readline
  - requests
  - rhash
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - sdl
  - sdl2
  - setuptools
  - sip
  - six
  - soapysdr
  - spdlog
  - sqlite
  - svt-av1
  - sysroot_linux-64
  - tk
  - toml
  - tzdata
  - uhd
  - unicodedata2
  - urllib3
  - volk
  - wheel
  - x264
  - x265
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxtst
  - xorg-recordproto
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - castxml
    - pygccxml
